# Generated by Django 5.0.1 on 2024-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
