# Generated by Django 5.0.1 on 2024-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                null=True, related_name="following", to="data.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="image"
            ),
        ),
    ]
