# Generated by Django 5.0.1 on 2024-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_alter_profile_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_bio",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
