# Generated by Django 5.0.1 on 2024-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_profile_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_facebook",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_instagram",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_website",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
