# Generated by Django 5.0.1 on 2024-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_userpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="post_image",
            field=models.ImageField(default=2, upload_to="post_image"),
            preserve_default=False,
        ),
    ]
