# Generated by Django 5.0.1 on 2024-04-19 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pic",
            name="user",
        ),
    ]
