# Generated by Django 5.0.1 on 2024-04-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0014_pic_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pic",
            name="image",
        ),
        migrations.AddField(
            model_name="pic",
            name="body",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
