# Generated by Django 5.0.1 on 2024-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0015_remove_pic_image_pic_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="pic",
            name="image",
            field=models.ImageField(default=2, upload_to="pic"),
            preserve_default=False,
        ),
    ]
