# Generated by Django 5.0.1 on 2024-04-19 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0016_pic_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pic",
            name="body",
        ),
    ]
