# Generated by Django 5.0.1 on 2024-04-19 09:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0017_remove_pic_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pic"),
        ),
        migrations.AlterField(
            model_name="pic",
            name="user",
            field=models.ForeignKey(
                default=django.contrib.auth.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
