# Generated by Django 5.0.1 on 2024-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0020_alter_pic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="Title",
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
