# Generated by Django 5.0.1 on 2024-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0021_userpost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="post_status",
            field=models.CharField(
                choices=[("Private", "private"), ("Public", "public")],
                default="public",
                max_length=20,
            ),
        ),
    ]
