# Generated by Django 5.0.1 on 2024-04-20 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0022_userpost_post_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="post_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="post_status",
            field=models.CharField(
                choices=[("Private", "Private"), ("Public", "Public")],
                default="Public",
                max_length=20,
            ),
        ),
    ]
