# Generated by Django 5.0.1 on 2024-04-23 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0028_remove_post_comment_commenrt_send_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pic",
        ),
    ]
